# 通用默认配置（所有任务共用）
env_id: SafetyPointGoal1-v0   # 会被 --env_id 覆盖
seed: 1

# 训练长度
steps_per_epoch: 30000
epochs: 200

# PPO 基本超参
lr: 0.0003
gamma: 0.99
gae_lambda: 0.95
clip_ratio: 0.2
n_policy_updates: 80
n_value_updates: 80
batch_size: 4096

# Safety Modulation 超参
d: 25.0
b: 3.0
eta: 2.0
e_max: 50
